server:
  port: 3000
  # Enable development mode
  # WARNING: Allows anyone to log in as a super admin
  dev_mode: true

db:
  url: sqlite:./db.sqlite
  jobs_url: sqlite:./jobs.sqlite

github:
  # Personal access token for public repo access
  token: ghp_abcd1234abcd1234abcd1234abcd1234abcd
